---
ms.openlocfilehash: 75fcd5b00ea5cac218a9f7809c53b179df97825c
ms.sourcegitcommit: 3fc033b6e98ed7ecdf46a85c79b00a3a3ddcf963
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 01/18/2019
ms.locfileid: "47229493"
---
# <a name="exceptions"></a><span data-ttu-id="01e0a-101">Exceções</span><span class="sxs-lookup"><span data-stu-id="01e0a-101">Exceptions</span></span>

<span data-ttu-id="01e0a-102">Exceções em c# fornecem uma maneira estruturada, uniforme e fortemente tipada de lidar com o nível de sistema e o nível de aplicativo condições de erro.</span><span class="sxs-lookup"><span data-stu-id="01e0a-102">Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions.</span></span> <span data-ttu-id="01e0a-103">O mecanismo de exceção no c# é muito semelhante do C++, com algumas diferenças importantes:</span><span class="sxs-lookup"><span data-stu-id="01e0a-103">The exception mechanism in C# is quite similar to that of C++, with a few important differences:</span></span>

*  <span data-ttu-id="01e0a-104">No c#, todas as exceções devem ser representadas por uma instância de um tipo de classe derivado de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="01e0a-104">In C#, all exceptions must be represented by an instance of a class type derived from `System.Exception`.</span></span> <span data-ttu-id="01e0a-105">No C++, qualquer valor de qualquer tipo pode ser usado para representar uma exceção.</span><span class="sxs-lookup"><span data-stu-id="01e0a-105">In C++, any value of any type can be used to represent an exception.</span></span>
*  <span data-ttu-id="01e0a-106">No c#, um bloco finally ([a instrução try](statements.md#the-try-statement)) pode ser usado para gravar o código de finalização que é executada em execução normal e condições excepcionais.</span><span class="sxs-lookup"><span data-stu-id="01e0a-106">In C#, a finally block ([The try statement](statements.md#the-try-statement)) can be used to write termination code that executes in both normal execution and exceptional conditions.</span></span> <span data-ttu-id="01e0a-107">Esse código é difícil escrever em C++ sem duplicação de código.</span><span class="sxs-lookup"><span data-stu-id="01e0a-107">Such code is difficult to write in C++ without duplicating code.</span></span>
*  <span data-ttu-id="01e0a-108">No c#, as exceções de nível de sistema, como estouro, divisão por zero e null desreferencia também definir classes de exceção em são juntamente com as condições de erro de nível de aplicativo.</span><span class="sxs-lookup"><span data-stu-id="01e0a-108">In C#, system-level exceptions such as overflow, divide-by-zero, and null dereferences have well defined exception classes and are on a par with application-level error conditions.</span></span>

## <a name="causes-of-exceptions"></a><span data-ttu-id="01e0a-109">Causas de exceções</span><span class="sxs-lookup"><span data-stu-id="01e0a-109">Causes of exceptions</span></span>

<span data-ttu-id="01e0a-110">Exceção pode ser gerada de duas maneiras diferentes.</span><span class="sxs-lookup"><span data-stu-id="01e0a-110">Exception can be thrown in two different ways.</span></span>

*  <span data-ttu-id="01e0a-111">Um `throw` instrução ([a instrução throw](statements.md#the-throw-statement)) gera uma exceção imediatamente e incondicionalmente.</span><span class="sxs-lookup"><span data-stu-id="01e0a-111">A `throw` statement ([The throw statement](statements.md#the-throw-statement)) throws an exception immediately and unconditionally.</span></span> <span data-ttu-id="01e0a-112">Controle nunca atinge a instrução imediatamente após o `throw`.</span><span class="sxs-lookup"><span data-stu-id="01e0a-112">Control never reaches the statement immediately following the `throw`.</span></span>
*  <span data-ttu-id="01e0a-113">Determinadas condições excepcionais que ocorrem durante o processamento de instruções em c# e expressão causam uma exceção em determinadas circunstâncias, quando a operação não pode ser concluída normalmente.</span><span class="sxs-lookup"><span data-stu-id="01e0a-113">Certain exceptional conditions that arise during the processing of C# statements and expression cause an exception in certain circumstances when the operation cannot be completed normally.</span></span> <span data-ttu-id="01e0a-114">Por exemplo, uma operação de divisão de inteiro ([operador de divisão](expressions.md#division-operator)) gera um `System.DivideByZeroException` se o denominador for zero.</span><span class="sxs-lookup"><span data-stu-id="01e0a-114">For example, an integer division operation ([Division operator](expressions.md#division-operator)) throws a `System.DivideByZeroException` if the denominator is zero.</span></span> <span data-ttu-id="01e0a-115">Ver [Classes de exceção comuns](exceptions.md#common-exception-classes) para obter uma lista das várias exceções que podem ocorrer dessa maneira.</span><span class="sxs-lookup"><span data-stu-id="01e0a-115">See [Common Exception Classes](exceptions.md#common-exception-classes) for a list of the various exceptions that can occur in this way.</span></span>

## <a name="the-systemexception-class"></a><span data-ttu-id="01e0a-116">A classe System. Exception</span><span class="sxs-lookup"><span data-stu-id="01e0a-116">The System.Exception class</span></span>

<span data-ttu-id="01e0a-117">O `System.Exception` classe é o tipo base de todas as exceções.</span><span class="sxs-lookup"><span data-stu-id="01e0a-117">The `System.Exception` class is the base type of all exceptions.</span></span> <span data-ttu-id="01e0a-118">Essa classe tem algumas propriedades importantes que compartilham todas as exceções:</span><span class="sxs-lookup"><span data-stu-id="01e0a-118">This class has a few notable properties that all exceptions share:</span></span>

*  <span data-ttu-id="01e0a-119">`Message` é uma propriedade somente leitura do tipo `string` que contém uma descrição legível do motivo da exceção.</span><span class="sxs-lookup"><span data-stu-id="01e0a-119">`Message` is a read-only property of type `string` that contains a human-readable description of the reason for the exception.</span></span>
*  <span data-ttu-id="01e0a-120">`InnerException` é uma propriedade somente leitura do tipo `Exception`.</span><span class="sxs-lookup"><span data-stu-id="01e0a-120">`InnerException` is a read-only property of type `Exception`.</span></span> <span data-ttu-id="01e0a-121">Se seu valor não for nulo, ele se refere à exceção que causou a exceção atual — ou seja, a exceção atual foi gerada em um bloco catch de tratamento de `InnerException`.</span><span class="sxs-lookup"><span data-stu-id="01e0a-121">If its value is non-null, it refers to the exception that caused the current exception—that is, the current exception was raised in a catch block handling the `InnerException`.</span></span> <span data-ttu-id="01e0a-122">Caso contrário, seu valor é nulo, indicando que essa exceção não foi causada por outra exceção.</span><span class="sxs-lookup"><span data-stu-id="01e0a-122">Otherwise, its value is null, indicating that this exception was not caused by another exception.</span></span> <span data-ttu-id="01e0a-123">O número de objetos de exceção encadeadas dessa maneira pode ser arbitrário.</span><span class="sxs-lookup"><span data-stu-id="01e0a-123">The number of exception objects chained together in this manner can be arbitrary.</span></span>

<span data-ttu-id="01e0a-124">O valor dessas propriedades pode ser especificado em chamadas para o construtor de instância para `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="01e0a-124">The value of these properties can be specified in calls to the instance constructor for `System.Exception`.</span></span>

## <a name="how-exceptions-are-handled"></a><span data-ttu-id="01e0a-125">Como as exceções são tratadas</span><span class="sxs-lookup"><span data-stu-id="01e0a-125">How exceptions are handled</span></span>

<span data-ttu-id="01e0a-126">As exceções são tratadas por um `try` instrução ([a instrução try](statements.md#the-try-statement)).</span><span class="sxs-lookup"><span data-stu-id="01e0a-126">Exceptions are handled by a `try` statement ([The try statement](statements.md#the-try-statement)).</span></span>

<span data-ttu-id="01e0a-127">Quando ocorre uma exceção, o sistema procura por mais próximo `catch` cláusula que pode manipular a exceção, conforme determinado pelo tipo da exceção de tempo de execução.</span><span class="sxs-lookup"><span data-stu-id="01e0a-127">When an exception occurs, the system searches for the nearest `catch` clause that can handle the exception, as determined by the run-time type of the exception.</span></span> <span data-ttu-id="01e0a-128">Primeiro, o método atual é procurado por um delimitador lexicalmente `try` instrução e as cláusulas catch associado da instrução try são considerados na ordem.</span><span class="sxs-lookup"><span data-stu-id="01e0a-128">First, the current method is searched for a lexically enclosing `try` statement, and the associated catch clauses of the try statement are considered in order.</span></span> <span data-ttu-id="01e0a-129">Se isso falhar, o método que chamou o método atual é procurado por um delimitador lexicalmente `try` instrução que inclui o ponto da chamada para o método atual.</span><span class="sxs-lookup"><span data-stu-id="01e0a-129">If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method.</span></span> <span data-ttu-id="01e0a-130">Essa pesquisa continua até que um `catch` cláusula for encontrada, que pode lidar com a exceção atual, nomeando uma classe de exceção que é da mesma classe ou uma classe base, do tipo de tempo de execução da exceção sendo lançada.</span><span class="sxs-lookup"><span data-stu-id="01e0a-130">This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown.</span></span> <span data-ttu-id="01e0a-131">Um `catch` cláusula que não nomeie uma classe de exceção pode lidar com qualquer exceção.</span><span class="sxs-lookup"><span data-stu-id="01e0a-131">A `catch` clause that doesn't name an exception class can handle any exception.</span></span>

<span data-ttu-id="01e0a-132">Depois que uma cláusula catch correspondente for encontrada, o sistema se prepara para transferir o controle para a primeira instrução da cláusula catch.</span><span class="sxs-lookup"><span data-stu-id="01e0a-132">Once a matching catch clause is found, the system prepares to transfer control to the first statement of the catch clause.</span></span> <span data-ttu-id="01e0a-133">Antes de inicia a execução da cláusula catch, o sistema primeiro executará, em ordem, qualquer `finally` cláusulas que estavam associadas a mais de instruções try aninhados que daquela que capturou a exceção.</span><span class="sxs-lookup"><span data-stu-id="01e0a-133">Before execution of the catch clause begins, the system first executes, in order, any `finally` clauses that were associated with try statements more nested that than the one that caught the exception.</span></span>

<span data-ttu-id="01e0a-134">Se nenhuma cláusula catch correspondente for encontrada, ocorrerá uma das duas coisas:</span><span class="sxs-lookup"><span data-stu-id="01e0a-134">If no matching catch clause is found, one of two things occurs:</span></span>

*  <span data-ttu-id="01e0a-135">Se a pesquisa por uma cláusula catch correspondente atingir um construtor estático ([construtores estáticos](classes.md#static-constructors)) ou inicializador de campo estático, em seguida, um `System.TypeInitializationException` é lançada no ponto em que disparou a invocação do construtor estático.</span><span class="sxs-lookup"><span data-stu-id="01e0a-135">If the search for a matching catch clause reaches a static constructor ([Static constructors](classes.md#static-constructors)) or static field initializer, then a `System.TypeInitializationException` is thrown at the point that triggered the invocation of the static constructor.</span></span> <span data-ttu-id="01e0a-136">A exceção interna do `System.TypeInitializationException` contém a exceção que foi originalmente lançada.</span><span class="sxs-lookup"><span data-stu-id="01e0a-136">The inner exception of the `System.TypeInitializationException` contains the exception that was originally thrown.</span></span>
*  <span data-ttu-id="01e0a-137">Se a pesquisa para correspondência de cláusulas catch atingir o código que inicialmente iniciou o thread, a execução do thread é encerrada.</span><span class="sxs-lookup"><span data-stu-id="01e0a-137">If the search for matching catch clauses reaches the code that initially started the thread, then execution of the thread is terminated.</span></span> <span data-ttu-id="01e0a-138">O impacto de tal rescisão é definido pela implementação.</span><span class="sxs-lookup"><span data-stu-id="01e0a-138">The impact of such termination is implementation-defined.</span></span>

<span data-ttu-id="01e0a-139">As exceções que ocorrem durante a execução do destruidor estão merece atenção especial.</span><span class="sxs-lookup"><span data-stu-id="01e0a-139">Exceptions that occur during destructor execution are worth special mention.</span></span> <span data-ttu-id="01e0a-140">Se ocorrer uma exceção durante a execução do destruidor e essa exceção não é capturada, em seguida, a execução do que o destruidor é terminada e o destruidor da classe base (se houver) é chamado.</span><span class="sxs-lookup"><span data-stu-id="01e0a-140">If an exception occurs during destructor execution, and that exception is not caught, then the execution of that destructor is terminated and the destructor of the base class (if any) is called.</span></span> <span data-ttu-id="01e0a-141">Se não houver nenhuma classe base (como no caso do `object` tipo) ou se não há nenhum destruidor de classe base, a exceção é descartada.</span><span class="sxs-lookup"><span data-stu-id="01e0a-141">If there is no base class (as in the case of the `object` type) or if there is no base class destructor, then the exception is discarded.</span></span>

## <a name="common-exception-classes"></a><span data-ttu-id="01e0a-142">Classes de exceção comuns</span><span class="sxs-lookup"><span data-stu-id="01e0a-142">Common Exception Classes</span></span>

<span data-ttu-id="01e0a-143">As seguintes exceções são geradas por determinadas operações de c#.</span><span class="sxs-lookup"><span data-stu-id="01e0a-143">The following exceptions are thrown by certain C# operations.</span></span>

|                                      |                |
|--------------------------------------|----------------|
| `System.ArithmeticException`         | <span data-ttu-id="01e0a-144">Uma classe base para exceções que ocorrem durante operações aritméticas, tais como `System.DivideByZeroException` e `System.OverflowException`.</span><span class="sxs-lookup"><span data-stu-id="01e0a-144">A base class for exceptions that occur during arithmetic operations, such as `System.DivideByZeroException` and `System.OverflowException`.</span></span> | 
| `System.ArrayTypeMismatchException`  | <span data-ttu-id="01e0a-145">Gerada quando um armazenamento em uma matriz falha porque o tipo real do elemento armazenado é incompatível com o tipo real da matriz.</span><span class="sxs-lookup"><span data-stu-id="01e0a-145">Thrown when a store into an array fails because the actual type of the stored element is incompatible with the actual type of the array.</span></span> | 
| `System.DivideByZeroException`       | <span data-ttu-id="01e0a-146">Gerada quando ocorre uma tentativa de dividir um valor inteiro por zero.</span><span class="sxs-lookup"><span data-stu-id="01e0a-146">Thrown when an attempt to divide an integral value by zero occurs.</span></span> | 
| `System.IndexOutOfRangeException`    | <span data-ttu-id="01e0a-147">Gerada quando uma tentativa de indexar uma matriz por meio de um índice que é menor que zero ou fora dos limites da matriz.</span><span class="sxs-lookup"><span data-stu-id="01e0a-147">Thrown when an attempt to index an array via an index that is less than zero or outside the bounds of the array.</span></span> | 
| `System.InvalidCastException`        | <span data-ttu-id="01e0a-148">Gerada quando uma conversão explícita de um tipo base ou interface para um tipo derivado falha em tempo de execução.</span><span class="sxs-lookup"><span data-stu-id="01e0a-148">Thrown when an explicit conversion from a base type or interface to a derived type fails at run time.</span></span> | 
| `System.NullReferenceException`      | <span data-ttu-id="01e0a-149">Lançada quando um `null` referência é usada em uma forma que faz com que o objeto referenciado a ser necessária.</span><span class="sxs-lookup"><span data-stu-id="01e0a-149">Thrown when a `null` reference is used in a way that causes the referenced object to be required.</span></span> | 
| `System.OutOfMemoryException`        | <span data-ttu-id="01e0a-150">Gerada quando uma tentativa de alocar memória (via `new`) falhará.</span><span class="sxs-lookup"><span data-stu-id="01e0a-150">Thrown when an attempt to allocate memory (via `new`) fails.</span></span> | 
| `System.OverflowException`           | <span data-ttu-id="01e0a-151">Lançada quando uma operação aritmética em um contexto `checked` estoura.</span><span class="sxs-lookup"><span data-stu-id="01e0a-151">Thrown when an arithmetic operation in a `checked` context overflows.</span></span> | 
| `System.StackOverflowException`      | <span data-ttu-id="01e0a-152">Gerada quando a pilha de execução acaba tendo muitas chamadas de método pendente; normalmente um indicativo da recursão muito profunda ou irrestrita.</span><span class="sxs-lookup"><span data-stu-id="01e0a-152">Thrown when the execution stack is exhausted by having too many pending method calls; typically indicative of very deep or unbounded recursion.</span></span> | 
| `System.TypeInitializationException` | <span data-ttu-id="01e0a-153">Gerada quando um construtor estático lança uma exceção e não `catch` cláusulas existe para capturá-la.</span><span class="sxs-lookup"><span data-stu-id="01e0a-153">Thrown when a static constructor throws an exception, and no `catch` clauses exists to catch it.</span></span> | 
